from .anime import Anime
from .anime_genre import anime_genres
from .anime_studio import anime_studios
from .anime_synonym import AnimeSynonym
from .genre import Genre
from .studio import Studio
from .survey import Survey
from .survey_anime import survey_animes
from .survey_genre import SurveyGenre
from .user import User
from .watched_anime import WatchedAnime
