"""add cascade delete to survey relations

Revision ID: 3bfe13dac4b7
Revises: 41d39d81ee50
Create Date: 2026-05-26 20:26:26.722664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bfe13dac4b7'
down_revision: Union[str, Sequence[str], None] = '41d39d81ee50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('survey_animes_survey_id_fkey'), 'survey_animes', type_='foreignkey')
    op.create_foreign_key(None, 'survey_animes', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('survey_characters_survey_id_fkey'), 'survey_characters', type_='foreignkey')
    op.create_foreign_key(None, 'survey_characters', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('survey_genres_survey_id_fkey'), 'survey_genres', type_='foreignkey')
    op.create_foreign_key(None, 'survey_genres', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('surveys_user_id_fkey'), 'surveys', type_='foreignkey')
    op.create_foreign_key(None, 'surveys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('uq_users_username_lower'), table_name='users')
    op.drop_constraint(op.f('watched_animes_user_id_fkey'), 'watched_animes', type_='foreignkey')
    op.create_foreign_key(None, 'watched_animes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watched_animes', type_='foreignkey')
    op.create_foreign_key(op.f('watched_animes_user_id_fkey'), 'watched_animes', 'users', ['user_id'], ['id'])
    op.create_index(op.f('uq_users_username_lower'), 'users', [sa.literal_column('lower(username::text)')], unique=True)
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.create_foreign_key(op.f('surveys_user_id_fkey'), 'surveys', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'survey_genres', type_='foreignkey')
    op.create_foreign_key(op.f('survey_genres_survey_id_fkey'), 'survey_genres', 'surveys', ['survey_id'], ['id'])
    op.drop_constraint(None, 'survey_characters', type_='foreignkey')
    op.create_foreign_key(op.f('survey_characters_survey_id_fkey'), 'survey_characters', 'surveys', ['survey_id'], ['id'])
    op.drop_constraint(None, 'survey_animes', type_='foreignkey')
    op.create_foreign_key(op.f('survey_animes_survey_id_fkey'), 'survey_animes', 'surveys', ['survey_id'], ['id'])
    # ### end Alembic commands ###
