"""add case insensitive username index

Revision ID: 41d39d81ee50
Revises: 8b29b4ff5b3c
Create Date: 2026-05-21 20:13:45.781868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d39d81ee50'
down_revision: Union[str, Sequence[str], None] = '8b29b4ff5b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index('uq_users_username_lower', 'users', [sa.text('LOWER(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_users_username_lower', 'users')
    # ### end Alembic commands ###
